### ISSUE TITLE
Issue with elide_fill_value

### ISSUE THREAD

**Issue by unidesigner** [aschampion/n5gest#82]
If I run in the dev branch
`cargo run -- import my.n5 dataset '{"type": "gzip"}' 256,256,5 data/*.png --elide_fill_value 0 `
I get errors:
`thread &apos;&lt;unnamed&gt;&apos; panicked at &apos;attempt to multiply with overflow&apos;, /HOMEDIR/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.20.0/./src/buffer.rs:375:36`
However, I run n5gest on master with same parameters `n5gest import ...` the process works correctly. Any idea what may cause the 'multiply with overflow'?

**Comment by aschampion** [comment]
Strange, this is a bug in an upstream library, but it should be locked to the same version in dev and master still. In your dev branch copy try changing this one line:

```udiff
diff --git a/Cargo.toml b/Cargo.toml
index c382a25..5589701 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -34,7 +34,7 @@ structopt = "0.2"
 serde_plain = { version = "0.3", optional = true }

 [dependencies.image]
-version = "0.20"
+version = "0.21"
 # Don't include jpeg_rayon dependency, hdr which includes scoped_threadpool, or ico.
 default-features = false
 features = ["gif_codec", "jpeg", "png_codec", "pnm", "tga", "tiff", "webp", "bmp", "dxt"]
```

**Comment by aschampion** [comment]
Duh, the reason it wasn't happening in your master copy is that it's release mode and won't catch the integer overflow. Since you are overflowing, though, you should use the new version of image (that patch will select 0.21.3, the overflow was prevented in 0.21.1).

**Comment by aschampion** [comment]
After some tests, this should be fixed in dev. Reopen if not. `image` will get bumped again before the next release for other features, but at least the overflow is fixed for now.

**Comment by unidesigner** [comment]
Indeed, this works now. Thanks!
